[versions]
agp = "9.3.0"
bcv = "0.18.1"
dokka = "2.2.0"
mavenPublish = "0.37.0"
androidxAppcompat = "1.7.1"
androidxConstraintlayout = "2.2.1"
androidxCoreKtx = "1.19.0"
androidxTestCore = "1.7.0"
junit = "4.13.2"
ktlint = "14.2.0"
robolectric = "4.16.1"

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidxAppcompat" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidxConstraintlayout" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidxCoreKtx" }
androidx-test-core = { module = "androidx.test:core", version.ref = "androidxTestCore" }
junit = { module = "junit:junit", version.ref = "junit" }
kotlin-metadata-jvm = { module = "org.jetbrains.kotlin:kotlin-metadata-jvm", version = "2.4.10" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
binary-compatibility-validator = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "bcv" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "mavenPublish" }
